<?php

namespace app\actions;


use app\models\Comments;
use Yii;
use yii\base\Action;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class ViewCountersAction
 * @package common\modules\actions
 * @frontend ```HTML
 * <a href="#" data-type="100" data-id="12">Like</a>
 */
class CountersAction extends Action
{
    public $modelClassName;
    public $relationName;
    public $requestName = "id";
    private $_error;
    private $_success;
    private $_model;
    private $_count;
    /**
     * @return void
     */
    public function run()
    {

        if($this->turn){
            $this->model->unlink($this->relationName,Yii::$app->user->identity);
            $this->count--;
            $this->success = 'удачно';
        }else{
            $this->model->link($this->relationName,Yii::$app->user->identity);
            $this->count++;
            $this->success = 'удачно';
        }
        return $this->messages;
    }
    public function init()
    {
        $model = $this->modelClassName;
        $this->model  = $model::find()->where(['id'=>$this->getId()])->one();
        if(empty($this->model)){
            $this->error = "Model not found";
            $this->messages;
        }
    }

    /**
     * @return array
     */
    public function afterRun()
    {
        parent::afterRun(); // TODO: Change the autogenerated stub
        return $this->messages;
    }

    public function getId()
    {
        return Yii::$app->request->post($this->requestName);
    }


    /**
     * @return bool
     */
    public function beforeRun()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
//        parent::beforeRun(); // TODO: Change the autogenerated stub
//        if (!Yii::$app->request->isAjax) {
//            return false;
//        }
//        if (!Yii::$app->user->isGuest) {
//            return false;
//        }
//        if ( Yii::$app->request->post() == null) {
//            return false;
//        }
        return true;
    }

    /**
     * @return mixed
     */
    public function getError(){
        return $this->_error;
    }

    /**
     * @param $value
     * @return mixed
     */
    public function setError($value){
        return $this->_error = $value;
    }

    /**
     * @return mixed
     */
    public function getSuccess(){
        return $this->_success;
    }

    /**
     * @param $value
     * @return mixed
     */
    public function setSuccess($value){
        return $this->_success = $value;
    }

    /**
     * @return array
     */
    public function getMessages(){
        return [
            'error' => $this->error,
            'success' => $this->success,
            'count'=>$this->count
        ];
    }
    public function getCount(){
        return $this->_count;
    }
    public function setCount($value){
        return $this->_count = $value;
    }

    /**
     * @return mixed
     */
    public function getModel(){
        return $this->_model;
    }
    public function setModel($value){
        return $this->_model = $value;
    }

    /**
     * @return bool
     */
    public function getTurn(){
        $favorites= $this->model->{$this->relationName};
        $this->count = count($favorites);
        if($this->count){
            $users = ArrayHelper::getColumn($favorites,"id");
            if(in_array(Yii::$app->user->id,$users)){
                return true;
            }else{
                return false;
            }
        }else{
            return false;
        }
    }
}
