<?php

namespace app\actions;

use app\models\CompanyInfo;
use app\models\CompanyProfileEmployees;
use Yii;
use yii\base\Action;
use yii\base\Model;

class ManyToManyLinkAction extends Action
{

    /*
     * Аттрибут для ошибки например $this->error = 'не удачно'
     */
    private $_error;
    /*
     * Аттрибут для удачного запроса например $this->success = 'удачно";
     */
    private $_success;
    /**
     *  этот аттрибут для relation например у моделя ест getFavorite() то завём 'relationName'=>'favorite
     */
    public $relationName;

    /**
     * Атррибут для модел метод ClassName; например modelClassName =>Model::className
     */
    public $modelClassName;
    /*
     * Аттрибут для динамического моделя
     */
    private $_model;

    public function beforeRun()
    {
        parent::beforeRun(); // TODO: Change the autogenerated stub
        if (Yii::$app->user->isGuest){return false;}
        if (empty($this->relationName)){return false;}
        if (empty($this->modelClassName)){return false;}
        if (!$this->model->load(Yii::$app->request->post())){return false;}
        return true;
    }

    public function init()
    {
        $this->model = new $this->modelClassName();
    }

    /**
     * @return mixed данная функция главное для исползованые
     *
     */

    public function run(){
        if($this->model->save()) {
            $this->linkData();
            Yii::$app->session->setFlash('nmessage', t('Successfuly'));
        }
        return $this->referer;
    }

    /**
     * сохранаят данные в релацию
     */

    public function linkData(){
     $this->company->link($this->relationName,$this->model);
    }

    /**
     * @return \yii\web\Response
     */
    public function getReferer() {
        return Yii::$app->controller->redirect(!empty(Yii::$app->request->referrer) ? Yii::$app->request->referrer : '/');
    }

    /**
     * @return mixed
     */
    public function getModel(){
        return $this->_model;
    }

    /**
     * @param $value
     * @return mixed
     */
    public function setModel($value){
        return $this->_model = $value;
    }
    public function getCompany(){
        return CompanyInfo::find()->user()->one();
    }
}